name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - "!**_test.go"  # exclude test files to ignore unit test changes
      - "e2e/**_test.go"  # include test files in e2e again
      - ".github/workflows/e2e-tests.yaml"

env:
  GO111MODULE: on
  GOFLAGS: -mod=vendor

jobs:
  test-full:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Smoke test
        working-directory: ./e2e
        run: |
          go test -v -ginkgo.v -timeout 3600s --ginkgo.label-filter=smoke

      - name: E2E test
        working-directory: ./e2e
        run: |
          go test -v -ginkgo.v -timeout 3600s --ginkgo.label-filter=e2e

      - name: Integration test
        working-directory: ./e2e
        run: |
          go test -v -ginkgo.v -timeout 3600s --ginkgo.label-filter=integration
